version: '3'

services:
  django:
    build:
      context: ../../
      dockerfile: compose/production/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ../../.envs/production
    command: /start
