version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/local
    ports:
      - "8000:8000"
    command: /start
