version: '3'

services:
  service:
    build:
      context: ../../
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../../service:/code
    env_file:
      - ../../.envs/local
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  {{cookiecutter.model_name}}-create:
    build:
      context: ../../
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../../service:/code
    env_file:
      - ../../.envs/local
    command: python manage.py run_function {{cookiecutter.model_name}}Create

  {{cookiecutter.model_name}}-update:
    build:
      context: ../../
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../../service:/code
    env_file:
      - ../../.envs/local
    command: python manage.py run_function {{cookiecutter.model_name}}Update

  {{cookiecutter.model_name}}-delete:
    build:
      context: ../../
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../../service:/code
    env_file:
      - ../../.envs/local
    command: python manage.py run_function {{cookiecutter.model_name}}Delete
